name: Deploy Montevideo Terminal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet packages
      run: nuget restore ObligatorioAppWeb.sln

    - name: Build the project
      run: msbuild ObligatorioAppWeb.sln /p:Configuration=Release /p:OutDir=D:/a/ObligatorioAppWeb/ObligatorioAppWeb/web/Release/
      
    - name: List directories
      run: ls -R D:\a\ObligatorioAppWeb\ObligatorioAppWeb\web
      
    - name: Upload to Server
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: montevideoterminal.somee.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./web/Release/_PublishedWebsites/web/
        server-dir: www.montevideoterminal.somee.com/
        cleanup: true
        
    - name: Update lastDeploy parameter
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
        path: './database/updateLastDeploy.sql'
