name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet packages
      run: nuget restore ObligatorioAppWeb.sln

    - name: Build the project
      run: msbuild ObligatorioAppWeb.sln /p:Configuration=Release /p:OutDir=D:/a/ObligatorioAppWeb/ObligatorioAppWeb/web/Release/
      
    - name: Listar archivos antes del despliegue
      run: ls -R D:\a\ObligatorioAppWeb\ObligatorioAppWeb\web
      
    - name: Upload to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: montevideoterminal.somee.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./web/Release/
        server-dir: www.montevideoterminal.somee.com/
