name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET Framework 4.0 Developer Pack
      run: |
        Invoke-WebRequest -Uri https://download.microsoft.com/download/4/6/4/4646C6F0-29C1-44F2-B979-92EDEAA7BF3D/NetFx4.0_ClientProfile.exe -OutFile NetFx4.0_ClientProfile.exe
        Start-Process -FilePath NetFx4.0_ClientProfile.exe -ArgumentList '/quiet /norestart' -NoNewWindow -Wait

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet packages
      run: nuget restore ObligatorioAppWeb.sln

    - name: Build the project
      run: msbuild ObligatorioAppWeb.sln /p:Configuration=Release

    - name: Upload to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: montevideoterminal.somee.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./bin/Release
        server-dir: www.montevideoterminal.somee.com/
